version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    external: true

  file_storage:
    name: file_storage
    external: true

networks:
  spark-network:
    name: ${PROJECT_NAME}-network
    external: true

services:
  spark-master:
    build:
      context: .
      dockerfile: spark-master.Dockerfile
    container_name: spark-master
    ports:
    - 8083:8080
    - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
      - file_storage:/opt/file_storage/
      # - file_storage/processed/:/opt/file_storage/processed/
    networks:
      - spark-network
    # user: "${DOCKER_USER}"
  
  spark-worker-1:
    build:
      context: .
      dockerfile: spark-worker.Dockerfile
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=2g
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
      - file_storage:/opt/file_storage/
    depends_on:
      - spark-master
    networks:
      - spark-network
    # user: "${DOCKER_USER}"

  spark-worker-2:
    build:
      context: .
      dockerfile: spark-worker.Dockerfile
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=2g
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
      - file_storage:/opt/file_storage/
    depends_on:
      - spark-master
    networks:
      - spark-network
    # user: "${DOCKER_USER}"

  
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - spark-network
    # user: "${DOCKER_USER}"